server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/test_schema?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  instance:
    hostname: host.docker.internal
  client:
    service-url:
      default-zone: http://host.docker.internal:8761/eureka/