server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/test_schema?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka/